services:
  db:
    image: postgres:16-alpine # Versão estável e leve
    container_name: FullStackHubLabs_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-minhasenha123}
      POSTGRES_DB: ${POSTGRES_DB:-FullStackHubLabs}
    ports:
      - '5432:5432' # Porta padrão que o Prisma vai procurar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
